### ISSUE TITLE
Forced counting can be bypassed by editing/deleting

### ISSUE THREAD

**Issue by Erisa** [Erisa/Lykos#1]
The forced counting experiment can be broken by editing the latest message, or altering history by editing previous messages.
You can also delete or edit previous messages, messing up history.

**Comment by spotlightishere** [comment]
Sounds like the latest message could be tracked? We could reference against the message above, increment and then send again to keep integrity if needed.

Wouldn't solve history manipulation however..

**Comment by Erisa** [comment]
I thought about tracking the latest message and retesting it on edit, however it wouldnt solve history manipulation at all.

**Comment by Erisa** [comment]
Wow I sure do love when I click Close and comment instead of Comment.
